
name: Build using PlatformIO

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          #- env: openevse_1-6-14
          #  python: 2.x
          #  platformio: 4.3.4
          #- env: openevse_1-6-17
          #  python: 2.x
          #  platformio: 4.3.4
          - env: openevse_1-6-23
            python: 3.x
            platformio: 5.2.3
          - env: openevse_latest
            python: 3.x
            platformio: 5.2.3
          - env: openevse
            python: 3.x
            platformio: 5.2.3
          - env: openevse_eu
            python: 3.x
            platformio: 5.2.3
          - env: emonevse
            python: 3.x
            platformio: 5.2.3
          - env: emonevse_3ph
            python: 3.x
            platformio: 5.2.3

    steps:
    - uses: actions/checkout@v2

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ matrix.env }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.env }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ matrix.env }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '${{ matrix.python }}'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio==${{ matrix.platformio }}

    - name: Run PlatformIO
      run: pio run -e ${{ matrix.env }}

    - name: Get compiler and output info
      run: |
        NAME=${{ matrix.env }}
        BUILT_TOOL=Platform IO
        TOOLCHAIN=~/.platformio/packages/toolchain-atmelavr
        AVR_CORE_DIR=~/.platformio/packages/framework-arduino*avr
        ELF=.pio/build/${{ matrix.env }}/firmware.elf
        HEX=.pio/build/${{ matrix.env }}/firmware.hex

        source ci/info_common.sh info.json

    - name: Upload output to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.env }}
        path: |
          .pio/build/${{ matrix.env }}/firmware.hex
          info.json
